// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(AplicationContext))]
    [Migration("20200314192041_UserUpdate-UniqueName")]
    partial class UserUpdateUniqueName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.Car", b =>
                {
                    b.Property<Guid>("CarId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<Guid?>("ChassisId")
                        .IsRequired();

                    b.Property<Guid?>("EngineId")
                        .IsRequired();

                    b.HasKey("CarId");

                    b.HasIndex("Brand")
                        .IsUnique()
                        .HasFilter("[Brand] IS NOT NULL");

                    b.HasIndex("ChassisId");

                    b.HasIndex("EngineId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Domain.Models.CarUser", b =>
                {
                    b.Property<Guid>("CarUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CarId");

                    b.Property<Guid>("UserId");

                    b.HasKey("CarUserId");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("CarUser");
                });

            modelBuilder.Entity("Domain.Models.Chassis", b =>
                {
                    b.Property<Guid>("ChassisId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeNumber");

                    b.Property<string>("Description");

                    b.HasKey("ChassisId");

                    b.HasIndex("CodeNumber")
                        .IsUnique()
                        .HasFilter("[CodeNumber] IS NOT NULL");

                    b.ToTable("Chassiss");
                });

            modelBuilder.Entity("Domain.Models.Engine", b =>
                {
                    b.Property<Guid>("EngineId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CylindersNumber");

                    b.Property<string>("Description");

                    b.HasKey("EngineId");

                    b.HasIndex("CylindersNumber")
                        .IsUnique();

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("UserId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.Car", b =>
                {
                    b.HasOne("Domain.Models.Chassis", "Chassis")
                        .WithMany("Cars")
                        .HasForeignKey("ChassisId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.Engine", "Engine")
                        .WithMany("Cars")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Models.CarUser", b =>
                {
                    b.HasOne("Domain.Models.Car", "Car")
                        .WithMany("CarsUsers")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("CarsUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
